name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt install g++

    - name: Compile the program
      run: g++ main.cpp -o kereta

    - name: Run the program (non-interaktif)
      run: ./kereta < /dev/null
